image:
  repository: ghcr.io/andrewknoesen/virtual-business-card
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
