image:
  repository: ghcr.io/andrewknoesen/virtual-business-card
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 2

ingress:
    enabled: true
    className: "traefik"
    hosts:
      - host: k3s.knoesen.link
        paths:
          - path: /
            pathType: Prefix
service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 192.168.0.251

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
