image:
  repository: ghcr.io/andrewknoesen/virtual-business-card
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 80

autoscaling:
  enabled: false
