name: Release and Build

on:
  push:
    tags:
      - "v*.*.*" # Trigger on tags like v1.0.0, v2.1.3, etc.

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/virtual-business-card

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: |
          # Remove 'v' prefix from tag (v1.0.0 -> 1.0.0)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION}"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Full semver (1.2.3)
            type=semver,pattern={{version}}
            # Major.minor (1.2)
            type=semver,pattern={{major}}.{{minor}}
            # Major version (1)
            type=semver,pattern={{major}}
            # Latest tag
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./virtual_business_card
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Helm chart
        run: |
          VERSION=${{ steps.version.outputs.version }}

          # Update image tag in values.yaml
          sed -i "s|tag: .*|tag: \"${VERSION}\"|" helm/virtual-business-card/values.yaml

          # Update Helm chart version
          sed -i "s|version: .*|version: ${VERSION}|" helm/virtual-business-card/Chart.yaml
          sed -i "s|appVersion: .*|appVersion: \"${VERSION}\"|" helm/virtual-business-card/Chart.yaml

      - name: Commit updated Helm chart
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add helm/virtual-business-card/values.yaml helm/virtual-business-card/Chart.yaml
          git commit -m "chore: bump chart version to ${{ steps.version.outputs.version }}"
          git push origin HEAD:main

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## Docker Images
            - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}`
            - `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest`
          draft: false
          prerelease: false
